### ISSUE TITLE
Proposed delineation of work

### ISSUE THREAD

**Issue by jravellana** [IntroToCode/RecipesCodemates10#2]
## 💬 Discussion topic

Suggested ownership of recipes for our group!

## ❗ Potential issues

Need to determine if there are any character limits or file type 

## 👥 People to consult

@maryyyao and @anjuved - any edits or alternate plans? 

## 📃 Details

Luke: Breakfast
Mary: Lunch
Anjani: Dinner

Search for an interesting recipe to add, fork your own repository to work on populating the recipe, and then issue a pull request.  Anyone can then further edit recipes! 

Criteria: Interesting and delicious sounding, easy to follow, low effort, and fun!

**Comment by maryyyao** [comment]
Good plan! @jravellana can be code review

**Comment by anjuved** [comment]
Sounds good! I'll do dinner.

Here is the recipe I'll add. 

1 jar pasta sauce
1 pack of spaghetti
1  cup parmesan cheese

Boil water. Add the pack of spaghetti. Boil for 6-10 minutes until tender. 
Add pasta sauce. 
Top with cheese.

**Comment by jravellana** [comment]
Going to propose adding titles to your recipe with an emoji! Feel free to throw out other ideas for "acceptance criteria," in addition to what's listed in the template
