### ISSUE TITLE
Dinner recipe sucks - please help!

### ISSUE THREAD

**Issue by anjuved** [IntroToCode/RecipesCodemates10#5]
## 💬 Discussion topic

My dinner recipe isn't the best - can someone review and make it better? 

## ❗ Potential issues

I'm an awful cook, so my dinner recipe isn't the best. 

## 👥 People to consult

@maryyyao @jravellana 

## 📃 Details

Please add some more instructions or better ingredients!

**Comment by jravellana** [comment]
Made some edits to the dinner request and placed you as a reviewer @anjuved!

**Comment by anjuved** [comment]
Amazing, loved the edits - thank you @jravellana ! 😄
